version: '3'
services:
#postgres
  postgres:
    image: "postgres"
    container_name: postgres_api-with-rabbitmq
    environment:
      - POSTGRES_USER=foobar
      - POSTGRES_PASSWORD=foobar
      - POSTGRES_DB=foobar
    ports:
      - "5432:5432"
    networks:
      backend:
        ipv4_address: 172.33.0.2
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # command: ["sh", "-c", "chmod -R 777 /var/lib/postgresql/data"]
#pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_api-with-rabbitmq
    environment:
      PGADMIN_DEFAULT_EMAIL: "foobar@foobar.com"
      PGADMIN_DEFAULT_PASSWORD: "foobar"
    ports:
      - "54321:80"
    networks:
      backend:
        ipv4_address: 172.33.0.3
    volumes:
       - ./configs_pgadmin/servers.json:/pgadmin4/servers.json
       - ./configs_pgadmin/pgpass:/pgpass
    depends_on:
      - postgres
#rabbit-mq
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_api-with-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      backend:
        ipv4_address: 172.33.0.4
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    depends_on:
      - postgres
#go-app
  app:
    build:
      context: .
      dockerfile: golang.Dockerfile
    image: app-foobar
    container_name: app_api-with-rabbitmq
    restart: unless-stopped
    tty: true
    ports:
      - "9000"
    networks:
      backend:
        ipv4_address: 172.33.0.5
    depends_on:
      - postgres
      - rabbitmq

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.33.0.0/24
         gateway: 172.33.0.1
